#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jan 28 19:24:36 2018

@author: albertzhang
"""

import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import load_iris 
iris_dataset = load_iris()


sl=list()
sw=list()
pl=list()
pw=list()
y = iris_dataset['target']

for i in range(len(iris_dataset['data'])):
    sl.append(iris_dataset['data'][i][0])
    sw.append(iris_dataset['data'][i][1])
    pl.append(iris_dataset['data'][i][2])
    pw.append(iris_dataset['data'][i][3])

fig, axes = plt.subplots(4,4,figsize=(15,15))
axes[0,0].hist(sl,bins=20)
axes[0,0].set_xlabel('sepal length(cm)')
axes[0,0].set_ylabel('sepal length(cm)')
axes[0,1].scatter(sw,sl,c=y,marker='o')
axes[0,1].scatter([],[],c='#451146',marker='o',label='setosa')
axes[0,1].scatter([],[],c='#fef700',marker='o',label='versicolor')
axes[0,1].scatter([],[],c='#45a796',marker='o',label='virginica')
axes[0,1].set_xlabel('sepal width(cm)')
axes[0,1].set_ylabel('petal length(cm)')
axes[0,1].legend()
axes[0,2].scatter(pl,sl,c=y,marker='o')
axes[0,2].scatter([],[],c='#451146',marker='o',label='setosa')
axes[0,2].scatter([],[],c='#fef700',marker='o',label='versicolor')
axes[0,2].scatter([],[],c='#45a796',marker='o',label='virginica')
axes[0,2].set_xlabel('petal length(cm)')
axes[0,2].set_ylabel('sepal length(cm)')
axes[0,2].legend()
axes[0,3].scatter(pw,sl,c=y,marker='o')
axes[0,3].scatter([],[],c='#451146',marker='o',label='setosa')
axes[0,3].scatter([],[],c='#fef700',marker='o',label='versicolor')
axes[0,3].scatter([],[],c='#45a796',marker='o',label='virginica')
axes[0,3].set_xlabel('petal width(cm)')
axes[0,3].set_ylabel('sepal length(cm)')
axes[0,3].legend()
axes[1,0].scatter(sl,sw,c=y,marker='o')
axes[1,0].scatter([],[],c='#451146',marker='o',label='setosa')
axes[1,0].scatter([],[],c='#fef700',marker='o',label='versicolor')
axes[1,0].scatter([],[],c='#45a796',marker='o',label='virginica')
axes[1,0].set_xlabel('sepal length(cm)')
axes[1,0].set_ylabel('sepal width(cm)')
axes[1,0].legend()
axes[1,1].hist(sw,bins=20)
axes[1,1].set_xlabel('sepal width(cm)')
axes[1,1].set_ylabel('sepal width(cm)')
axes[1,2].scatter(pl,sw,c=y,marker='o')
axes[1,2].scatter([],[],c='#451146',marker='o',label='setosa')
axes[1,2].scatter([],[],c='#fef700',marker='o',label='versicolor')
axes[1,2].scatter([],[],c='#45a796',marker='o',label='virginica')
axes[1,2].set_xlabel('petal length(cm)')
axes[1,2].set_ylabel('sepal width(cm)')
axes[1,2].legend()
axes[1,3].scatter(pw,sw,c=y,marker='o')
axes[1,3].scatter([],[],c='#451146',marker='o',label='setosa')
axes[1,3].scatter([],[],c='#fef700',marker='o',label='versicolor')
axes[1,3].scatter([],[],c='#45a796',marker='o',label='virginica')
axes[1,3].set_xlabel('petal width(cm)')
axes[1,3].set_ylabel('sepal width(cm)')
axes[1,3].legend()
axes[2,0].scatter(sl,pl,c=y,marker='o')
axes[2,0].scatter([],[],c='#451146',marker='o',label='setosa')
axes[2,0].scatter([],[],c='#fef700',marker='o',label='versicolor')
axes[2,0].scatter([],[],c='#45a796',marker='o',label='virginica')
axes[2,0].legend()
axes[2,0].set_xlabel('sepal length(cm)')
axes[2,0].set_ylabel('petal length(cm)')
axes[2,1].scatter(sw,pl,c=y,marker='o')
axes[2,1].scatter([],[],c='#451146',marker='o',label='setosa')
axes[2,1].scatter([],[],c='#fef700',marker='o',label='versicolor')
axes[2,1].scatter([],[],c='#45a796',marker='o',label='virginica')
axes[2,1].legend()
axes[2,1].set_xlabel('sepal width(cm)')
axes[2,1].set_ylabel('petal length(cm)')
axes[2,2].hist(pl,bins=20)
axes[2,2].set_xlabel('petal length(cm)')
axes[2,2].set_ylabel('petal length(cm)')
axes[2,3].scatter(pw,pl,c=y,marker='o')
axes[2,3].scatter([],[],c='#451146',marker='o',label='setosa')
axes[2,3].scatter([],[],c='#fef700',marker='o',label='versicolor')
axes[2,3].scatter([],[],c='#45a796',marker='o',label='virginica')
axes[2,3].set_xlabel('petal width(cm)')
axes[2,3].set_ylabel('petal length(cm)')
axes[2,3].legend()
axes[3,0].scatter(sl,pw,c=y,marker='o')
axes[3,0].scatter([],[],c='#451146',marker='o',label='setosa')
axes[3,0].scatter([],[],c='#fef700',marker='o',label='versicolor')
axes[3,0].scatter([],[],c='#45a796',marker='o',label='virginica')
axes[3,0].set_xlabel('sepal length(cm)')
axes[3,0].set_ylabel('petal width(cm)')
axes[3,0].legend()
axes[3,1].scatter(sw,pw,c=y,marker='o')
axes[3,1].scatter([],[],c='#451146',marker='o',label='setosa')
axes[3,1].scatter([],[],c='#fef700',marker='o',label='versicolor')
axes[3,1].scatter([],[],c='#45a796',marker='o',label='virginica')
axes[3,1].set_xlabel('sepal width(cm)')
axes[3,1].set_ylabel('petal width(cm)')
axes[3,1].legend()
axes[3,2].scatter(pl,pw,c=y,marker='o')
axes[3,2].scatter([],[],c='#451146',marker='o',label='setosa')
axes[3,2].scatter([],[],c='#fef700',marker='o',label='versicolor')
axes[3,2].scatter([],[],c='#45a796',marker='o',label='virginica')
axes[3,2].set_xlabel('petal length(cm)')
axes[3,2].set_ylabel('petal length(cm)')
axes[3,2].legend()
axes[3,3].hist(pw,bins=20)
axes[3,3].set_xlabel('petal width(cm)')
axes[3,3].set_ylabel('petal width(cm)')
plt.savefig('task32.png')
plt.show()

